name = "Etch less coffee"
description = "Theme for less.coffee"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]

[author]
  name = "Arie Oldman (forked from Lukas Joswiak)"
  homepage = "https://less.coffee"

[taxonomies]
 tag = "tags"
